# Generated by Django 4.2.8 on 2024-01-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='post_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
