# Generated by Django 4.2.8 on 2024-01-04 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0002_blog_post_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogHashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBlog.blog')),
                ('hashtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBlog.hashtag')),
            ],
            options={
                'ordering': ['blog', 'hashtag'],
                'unique_together': {('blog', 'hashtag')},
            },
        ),
    ]
