# Generated by Django 4.2.8 on 2024-01-04 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0003_hashtag_bloghashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='hashtags',
            field=models.ManyToManyField(to='AppBlog.hashtag'),
        ),
        migrations.DeleteModel(
            name='BlogHashtag',
        ),
    ]
